server:
  port: 8001
  
mybatis:
  type-aliases-package: com.holt.spirngcloud.entities    # 所有Entity别名类所在包
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true                      #开其数据库下划线字段转驼峰    
spring:
   application:
    name: mymicroservicecloud-dept 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456
    #datasource:   #   data:                                                 #自动添加表数据到数据库    #  - classpath:sql/*-data.sql    #schema:    #- classpath:sql/*-table.sql                                   #自动构建classpath/sql目录下的sql脚本
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200 