server:
  port: 8001
  
mybatis:
  type-aliases-package: com.holt.spirngcloud.entities    # 所有Entity别名类所在包
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true                      #开其数据库下划线字段转驼峰    
    
    
spring:
   application:
    name: mymicroservicecloud-dept 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456
    
    
    #datasource:
   #   data:                                                 #自动添加表数据到数据库    #  - classpath:sql/*-data.sql    #schema:    #- classpath:sql/*-table.sql                                   #自动构建classpath/sql目录下的sql脚本     #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
#       开启后台监控
        enabled: true
        url-pattern: /druid/*
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
# eureka 的注册地址 
eureka:  client:    serviceUrl:#     defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/

  instance:    instance-id: mymicroservicecloud-dept:8001   #修改eureka中显示服务的名称    prefer-ip-address: true                     #访问的路径可以显示ip

#配置微服务的信息
info:
 app.name: holt.mymicroservice
 company.name: www.holt.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$

  
     
            
         