server:
  port: 80
  
eureka:  client:    register-with-eureka: false        #不将该客户端注册进Eureka     serviceUrl:      defaultZone: http://eureka7002.com:7002/eureka/
      #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/