server:
  port: 9527
  
  
spring:  application:    name: mymicroservicecloud-zuul-geteway 
  
#将zuul注册进eureka
eureka:   client:     service-url:      defaultZone: http://eureka7001.com:7001/eureka/   #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: mymicroservicecloud-zuul-geteway9527   #修改eureka中显示服务的名称
    prefer-ip-address: true                             #Eureka显示ip地址和端口     
#
zuul: 
  prefix: /holt             #访问/mydept时加上这个前缀  ：/holt/mydept       
  ignored-services: "*"     #隐藏所有微服务名  routes:     mypath.serviceId: mymicroservicecloud-dept
    mypath.path: /mydept/**
    

                     #访问的路径可以显示ip

#配置微服务的信息
info:
 app.name: holt.mymicroservice-zuul
 company.name: www.holt.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$
 
